import { Report } from './domain';

export const escapeHtml=(value:unknown)=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));

const state=(reviewed:boolean,excluded:boolean)=>excluded?'Исключена':reviewed?'Отработана':'В работе';
const imageCell=(src:string,name:string)=>src?`<a href="${escapeHtml(src)}" target="_blank" title="Открыть снимок"><img src="${escapeHtml(src)}" alt="Снимок ${escapeHtml(name)}"></a>`:'—';

export function reportHtml(report:Report):string {
  const e=escapeHtml;
  let number=0;
  const rows=report.tests.flatMap(test=>test.clashes.map(clash=>{
    number++;
    const workState=state(clash.reviewed,clash.excluded);
    const search=[number,clash.name,test.name,workState,clash.status,clash.group,clash.note,clash.point?.join(' '),...clash.elements.flatMap(item=>[item.name,item.id,item.guid,item.source,...Object.values(item.properties)]),...Object.values(clash.properties)].join(' ').toLowerCase();
    return `<tr data-state="${e(workState)}" data-test="${e(test.name)}" data-search="${e(search)}"><td>${number}</td><td><strong>${e(clash.name||`Коллизия ${number}`)}</strong></td><td>${e(test.name)}</td><td><span class="state ${clash.excluded?'excluded':clash.reviewed?'done':'work'}">${e(workState)}</span><small>${clash.enabled?'Знак показывается':'Знак скрыт'}</small></td><td>${e(clash.status||'—')}</td><td>${e(clash.group||'—')}</td><td>${e(clash.note||'—')}</td><td>${e(clash.point?.map(value=>Number(value.toFixed(3))).join('; ')||'—')}<small>${e(clash.distance)}</small></td><td>${imageCell(report.images[clash.image]||'',clash.name)}</td><td>${clash.elements.map((item,index)=>`<div class="object"><b>Элемент ${index+1}</b><span>${e(item.name||item.id||'—')}</span><small>${e(item.source||'—')}</small><code>${e(item.guid||'GUID отсутствует')}</code></div>`).join('')}</td></tr>`;
  })).join('');
  const tests=report.tests.filter(test=>test.clashes.length).map(test=>`<option value="${e(test.name)}">${e(test.name)}</option>`).join('');
  return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(report.name)} — отчёт о коллизиях</title><style>
  :root{color-scheme:light;font:14px/1.4 "Segoe UI",Arial,sans-serif;color:#172336;background:#f3f6fa}*{box-sizing:border-box}body{margin:0}.head{position:sticky;top:0;z-index:5;background:#17202b;color:#fff;padding:18px 24px;box-shadow:0 2px 12px #0003}.head h1{margin:0 0 3px;font-size:24px}.head p{margin:0;color:#b9c5d3}.filters{display:grid;grid-template-columns:minmax(240px,1fr) 190px 220px auto;gap:10px;margin-top:15px}.filters input,.filters select,.filters button{height:38px;border:1px solid #536274;border-radius:6px;background:#242f3c;color:#fff;padding:0 11px;font:inherit}.filters button{cursor:pointer;background:#356fb9}.count{align-self:center;color:#dce5ef;white-space:nowrap}.table-wrap{padding:18px;overflow:auto}table{border-collapse:separate;border-spacing:0;width:100%;min-width:1500px;background:#fff;box-shadow:0 4px 22px #21314a1c}th{position:sticky;top:128px;z-index:3;background:#e5ebf2;color:#35465b;text-align:left;white-space:nowrap}th,td{border-right:1px solid #d9e0e8;border-bottom:1px solid #d9e0e8;padding:9px;vertical-align:top}td:first-child{width:55px;text-align:center}td:nth-child(2){min-width:170px}td:nth-child(7){min-width:220px;white-space:pre-wrap}td:nth-child(10){min-width:290px}tbody tr:hover td{background:#f2f7fc}small{display:block;color:#68788c;margin-top:3px}.state{display:inline-block;border-radius:999px;padding:3px 9px;font-weight:650}.state.work{background:#fff0c2;color:#6f5100}.state.done{background:#d9f4e5;color:#12683d}.state.excluded{background:#e4e7eb;color:#59616c}.object{display:grid;gap:2px;margin-bottom:10px}.object:last-child{margin-bottom:0}.object code{overflow-wrap:anywhere;color:#315f98}img{display:block;width:150px;height:90px;object-fit:contain;background:#eef2f6;cursor:zoom-in}[hidden]{display:none!important}@media print{.head{position:static}.filters{display:none}.table-wrap{padding:0}th{position:static}tr{break-inside:avoid}body{background:#fff}}
  </style></head><body><header class="head"><h1>Отчёт о коллизиях</h1><p>${e(report.name)}</p><div class="filters"><input id="search" type="search" placeholder="Поиск по отчёту"><select id="state"><option value="">Все состояния</option><option>В работе</option><option>Отработана</option><option>Исключена</option></select><select id="test"><option value="">Все проверки</option>${tests}</select><button onclick="window.print()">Печать</button><span class="count" id="count"></span></div></header><div class="table-wrap"><table><thead><tr><th>№</th><th>Коллизия</th><th>Проверка</th><th>Состояние</th><th>Статус Navisworks</th><th>Группа / назначение</th><th>Комментарий</th><th>Координаты / расстояние</th><th>Снимок</th><th>Объекты модели</th></tr></thead><tbody id="rows">${rows}</tbody></table></div><script>
  const search=document.querySelector('#search'),state=document.querySelector('#state'),test=document.querySelector('#test'),rows=[...document.querySelectorAll('#rows tr')],count=document.querySelector('#count');function apply(){const q=search.value.trim().toLowerCase();let shown=0;for(const row of rows){const visible=(!q||row.dataset.search.includes(q))&&(!state.value||row.dataset.state===state.value)&&(!test.value||row.dataset.test===test.value);row.hidden=!visible;if(visible)shown++}count.textContent='Показано: '+shown+' из '+rows.length}search.addEventListener('input',apply);state.addEventListener('change',apply);test.addEventListener('change',apply);apply();
  </script></body></html>`;
}

export function download(name:string,content:string,type:string){const url=URL.createObjectURL(new Blob([content],{type}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
